name: skadi ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build & test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build & test skadi library
        run: ./gradlew skadi-lib:build

      - name: Build & test sample
        run: ./gradlew sample:build

      - name: Bintray upload dry run
        run: ./gradlew bintrayUpload --dry-run
