on:
  release:
    types: [published]

jobs:
  build:
    name: publish release on MavenCentral

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: MavenCentral upload
        run: ./gradlew skadi-lib:publish